# Numpy

* [part1](#40)
   * [what is Numpy](#41)
   * [ndarray对象](#42)
   * [Numpy对数组对基本操作](#43)

## 1）[what is Numpy？](#41)

-- 科学计算库
   可以省掉很多循环语句，代码使用方面比Python列表简单的多。

In [1]:
import numpy as np

## 2）[ndarray对象？](#42)

### 2.1）数组

In [2]:
# 如何创建数组 讲解数组的表现形式对应关系以及与Python列表的对比

a)

In [3]:
arr = [1, 2, 3]
np_arr = np.array(arr)
np_arr

array([1, 2, 3])

b)

In [4]:
np_arr = np.arange(1, 4) 
np_arr

array([1, 2, 3])

In [5]:
np_arr2d = np.arange(6).reshape(2, 3) 
np_arr2d

array([[0, 1, 2],
       [3, 4, 5]])

### 2.2）属性

In [15]:
# 维度

In [16]:
np_arr.ndim

1

In [18]:
np_arr2d.ndim

2

In [19]:
# 具体形状

In [20]:
np_arr.shape

(3,)

In [21]:
np_arr2d.shape

(2, 3)

In [22]:
# 元素数据类型

In [23]:
np_arr.dtype

dtype('int64')

In [24]:
np_arr2d.dtype

dtype('int64')

## 3）[Numpy 对数组对基本操作？](#43)

| 数学中的运算符 | 程序中的运算符号 |
|--------------|---------------|
| + | + |
| - | - |
| ✖️ | * |
| ➗| /|

#### 加

In [25]:
np_arr

array([1, 2, 3])

In [26]:
np_arr + np_arr

array([2, 4, 6])

#### 减

In [27]:
np_arr - np_arr

array([0, 0, 0])

#### 乘

In [28]:
np_arr * np_arr

array([1, 4, 9])

#### 除

In [29]:
np_arr / np_arr

array([1., 1., 1.])

**注意分母为0的情况**

In [30]:
np_arr / 0

/anaconda3/envs/kaggle/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf, inf, inf])