In [3]:
import numpy as np
a = np.array([[0, 1, 2, 3, 4], [9, 8, 7, 6, 5]])
a

array([[0, 1, 2, 3, 4],
       [9, 8, 7, 6, 5]])

In [4]:
print(a)

[[0 1 2 3 4]
 [9 8 7 6 5]]


In [5]:
a.ndim #维度

2

In [6]:
a.shape #具体形状

(2, 5)

In [7]:
a.size #元素个数

10

In [8]:
a.dtype #元素数据类型

dtype('int32')

In [9]:
a.itemsize #每个元素由几个字节构成

4

In [ ]:
数组创建：

In [10]:
x = np.array([0, 1, 2, 3]) #列表类型
print(x)

[0 1 2 3]


In [11]:
x = np.array((4, 5, 6, 7)) #元组类型
print(x)

[4 5 6 7]


In [13]:
x = np.array([[1, 2], [9, 8], (0.1, 0.2)]) #列表与元组混合类型
print(x)

[[1.  2. ]
 [9.  8. ]
 [0.1 0.2]]


In [14]:
np.arange(5) #元素从0到n-1

array([0, 1, 2, 3, 4])

In [16]:
np.ones((2, 3)) #全1数组

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.zeros((2, 3), dtype = np.int32) #全0数组

array([[0, 0, 0],
       [0, 0, 0]])

In [18]:
np.eye(3) #n*n单位阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
x = np.ones((2, 2, 3)) #(a,b,c) a个b*c矩阵
print(x)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [20]:
x.shape

(2, 2, 3)

In [23]:
a = np.linspace(1, 10, 4) #(start,stop,step)
a

array([ 1.,  4.,  7., 10.])

In [24]:
b = np.linspace(1, 10, 4, endpoint = False) #
b

array([1.  , 3.25, 5.5 , 7.75])

In [26]:
c = np.concatenate((a, b)) #合并数组
c

array([ 1.  ,  4.  ,  7.  , 10.  ,  1.  ,  3.25,  5.5 ,  7.75])

In [27]:
a = np.array([9, 8, 7, 6, 5])
a[2]  #索引

7

In [28]:
a[1 : 4 : 2] #切片 start:stop:step

array([8, 6])

In [30]:
a = np.arange(8).reshape((2, 2, 2)) (a,b,c) #2个2*2数组，从0到7
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [32]:
a[1,0,0] # 第1个数组，第[0][0]个元素

4

In [ ]:
数组运算：

In [34]:
a = np.arange(8).reshape((2,2,2))
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [35]:
np.square(a) # 各元素的平方

array([[[ 0,  1],
        [ 4,  9]],

       [[16, 25],
        [36, 49]]], dtype=int32)

In [36]:
a = np.sqrt(a) # 各元素的平方根
a

array([[[0.        , 1.        ],
        [1.41421356, 1.73205081]],

       [[2.        , 2.23606798],
        [2.44948974, 2.64575131]]])

In [ ]:
np.modf(a)