![title](img/part2.png)

In [31]:
import numpy as np

实例![title](img/栗子.png)

In [35]:
groupa = np.array([100, 91, 90, 84, 83, 82, 80, 60])  # 先给出实例a

In [36]:
groupa

array([100,  91,  90,  84,  83,  82,  80,  60])

## 索引

**场景描述：**

**小组a按成绩依次排名，
小组b未排序**

查询小组a的某个同学具体的成绩 ![title](img/成绩查询.png)

![title](img/索引.png)

![title](img/个人.png) 第一名的学生成绩是多少？

In [39]:
groupa[0] #索引

100

![title](img/个人.png) 第八名的学生成绩是多少？

In [40]:
groupa[7] # 索引

60

## 切片

**前五名的成绩都是多少？**  

![title](img/切片.png)

In [41]:
groupa[:5]

array([100,  91,  90,  84,  83])

In [63]:
groupa[1:5]

array([91, 90, 84, 83])

In [64]:
groupa[0:3:4]

array([100])

## 布尔索引

**场景描述：**
**现在有一个小组b里面存储的是未排序的成绩**

In [43]:
groupb = np.array([90, 80, 72, 83, 70, 56, 91, 60])
groupb

array([90, 80, 72, 83, 70, 56, 91, 60])

选出大于85的成绩都有哪些

In [44]:
groupb > 85 

array([ True, False, False, False, False, False,  True, False])

In [45]:
groupb[groupb > 85]

array([90, 91])

本质

In [46]:
choose = np.array([ True, True, True, True, True, False,  True, False])

In [47]:
groupb[choose]

array([90, 80, 72, 83, 70, 91])

## 高级索引

In [48]:
groupb[[1, 3, 0]]

array([80, 83, 90])

利用整数数组进行索引

In [49]:
groupb[[1, 3, 0]]

array([80, 83, 90])

In [50]:
group2d = groupb.reshape(2, 4)
group2d

array([[90, 80, 72, 83],
       [70, 56, 91, 60]])

![title](img/列表嵌套.png)

In [51]:
group2d[1][2]

91

In [61]:
group2d[1, 2]

91

In [53]:
group2d[0]

array([90, 80, 72, 83])

In [54]:
arr = np.arange(20).reshape(4, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [55]:
arr[[2, 3]]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [56]:
arr[[2, 3], [0, 1]]

array([10, 16])

## 随机数据

|方法|描述|
|---|---|
|numpy.random.randn()|从“标准正态”分布中返回一个或多个样本|
|numpy.random.randint(low, high, size)|返回low-high(high取不到)间的随机数|
|numpy.random.normal()|从正态（高斯）分布中抽取随机样本|
|numpy.random.rand()|返回0-1（1取不到）间的随机数|

In [62]:
np.random.rand()

0.9420130633677998

In [58]:
np.random.randint(0, 2)

0

In [59]:
np.random.randn(2, 3)

array([[ 0.28271136,  0.74146373, -0.21307319],
       [ 0.1090141 , -1.01034888, -0.08759461]])

In [60]:
np.random.normal(-1 , 1, size=(2, 3))

array([[ 1.19923813,  0.62032929, -0.19713303],
       [ 0.44346102,  0.16149408, -2.03398189]])