In [ ]:
一、创建数组：

In [4]:
import numpy as np

In [ ]:
方法一

In [6]:
arr = [1, 2, 3]
np_arr = np.array(arr)
np_arr

array([1, 2, 3])

In [ ]:
方法二

In [ ]:
一维

In [8]:
np_arr = np.arange(1,4)
np_arr

array([1, 2, 3])

In [ ]:
二维

In [10]:
np_arr2d = np.arange(9).reshape(3,3)
np_arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
二、属性：

In [ ]:
维度

In [11]:
np_arr.ndim

1

In [12]:
np_arr2d.ndim

2

In [ ]:
具体形状

In [13]:
np_arr.shape

(3,)

In [14]:
np_arr2d.shape

(3, 3)

In [ ]:
元素数据类型

In [15]:
np_arr.dtype

dtype('int32')

In [16]:
np_arr2d.dtype

dtype('int32')

In [17]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [ ]:
三、数组的算术运算：

In [21]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [22]:
arr + arr

array([ 2,  4,  6,  8, 10])

In [23]:
arr - arr

array([0, 0, 0, 0, 0])

In [24]:
arr * arr

array([ 1,  4,  9, 16, 25])

In [25]:
arr / arr

array([1., 1., 1., 1., 1.])

In [26]:
arr / 0

C:\Users\asus-1\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf, inf, inf, inf, inf])

In [29]:
group_a = np.array([100,98,95,92,88,86,80,77])
group_a

array([100,  98,  95,  92,  88,  86,  80,  77])

In [ ]:
第一名学生的成绩是多少？

In [30]:
group_a[0] #索引

100

In [ ]:
第八名学生的成绩是多少？

In [31]:
group_a[7] #索引

77

In [ ]:
前四名学生的成绩是多少？

In [32]:
group_a[:4]

array([100,  98,  95,  92])

In [ ]:
第五到七名学生的成绩是多少？

In [34]:
group_a[4:7]

array([88, 86, 80])

In [35]:
group_a[0:3:4] #group([start:stop:step])

array([100])

In [37]:
group_b = np.array([99, 66, 72, 88, 92, 95, 86, 93])
group_b

array([99, 66, 72, 88, 92, 95, 86, 93])

In [ ]:
选出大于90的成绩

In [38]:
group_b > 90

array([ True, False, False, False,  True,  True, False,  True])

In [39]:
group_b[group_b > 90]

array([99, 92, 95, 93])

In [ ]:
或者

In [40]:
choose = np.array([ True, False, False, False,  True,  True, False,  True])
group_b[choose]

array([99, 92, 95, 93])

In [44]:
group_b[[1, 4, 2]]

array([66, 92, 72])

In [47]:
group2d = group_b.reshape(2, 4)
group2d

array([[99, 66, 72, 88],
       [92, 95, 86, 93]])

In [48]:
group2d[1][2]

86

In [49]:
group2d[1, 2]

86

In [50]:
group2d[0]

array([99, 66, 72, 88])

In [51]:
group2d[1]

array([92, 95, 86, 93])

In [53]:
arr = np.arange(20).reshape(4, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [54]:
arr[[1,3]]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [55]:
arr[[1,3],[2,4]]

array([ 7, 19])

In [59]:
arr[[0,1,2],[0,3,2]]

array([ 0,  8, 12])

In [ ]:
随机数

In [60]:
np.random.rand()

0.7299142645616267

In [67]:
np.random.randint(0, 2)

1

In [68]:
np.random.randn(2, 3)

array([[ 0.79500873, -0.34805987, -1.07201859],
       [-0.44781152,  1.46057956,  0.05159091]])

In [71]:
np.random.normal(-1, 1, (2, 3))

array([[-0.7579711 ,  1.11127349, -0.74289837],
       [-1.833844  , -1.27318074, -1.48041916]])